language: python
python:
  - "3.6"

os:
  - linux
  - osx

dist: xenial
sudo: required

addons:
  snaps:
  - name: o2scl
    classic: true
    channel: latest/edge

addons:
  homebrew:
    taps: awsteiner/science
    packages:
    - o2scl

script:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      rvm use 2.3 --install --binary    
      brew update && brew install homebrew/science/hdf5 && brew tap awsteiner/science && which autoconf && brew install o2scl --HEAD -v && brew install python3 && pip3 install h5py && brew install freetype && brew install libpng && pip3 install matplotlib && pip3 install o2sclpy && o2graph -help ;
    fi

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
       pip install -r o2sclpy ;
    fi

notifications:
  email:
    on_success: never
    on_failure: never
