language: python
python:
  - "3.6"

# Note that travis doesn't support python on osx yet
os:
  - linux

dist: xenial
sudo: required

# This doesn't appear to work yet. It skips the snap install.
addons:
  snaps:
  - name: o2scl
    devmode: true
    channel: latest/edge

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
       pip install . && o2graph -help ;
    fi

notifications:
  email:
    on_success: never
    on_failure: never
