language: python
python:
  - "3.6"

# Note that travis doesn't support python on osx yet
os:
  - linux

dist: xenial
sudo: required

addons:
  snaps:
  - name: o2scl
    classic: true
    channel: latest/edge

addons:
  homebrew:
    taps: awsteiner/science
    packages:
    - o2scl

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
       pip install . && o2graph -help ;
    fi

notifications:
  email:
    on_success: never
    on_failure: never
